### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by sasiwithyou** [blueagler/QuillBot-Premium-Crack#10]
It keeps hooking up the premium, and it will never allow you to use the premium options even though the are visible.

**Comment by blueagler** [comment]
<img width="1792" alt="Screen Shot 2022-02-02 at 1 45 06 AM" src="https://user-images.githubusercontent.com/61572188/152021972-058ea47c-8172-4479-9989-2cc90f36feb7.png">
server will verify whether you  are premium, this can't be hooked...If anyone can give me cookies from a real premium account,I can do  this.
but word limit(300) and Synonyms restriction are verified locally...so they work fine
