### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by batashahh** [blueagler/QuillBot-Premium-Crack#2]
Great extension! I had been using it for a week when it stopped working. 
QuillBot is working when I open it in incognito, but when I use it with your extension active, it just doesn't paraphrase anything, although the premium badge still remains visible. 
Please see to it Sir/Ma'am, you've been a saviour for me this past week

https://user-images.githubusercontent.com/71149065/141683897-522eb27e-1f66-4be3-bbb2-2b30b8e35771.mp4

.

**Comment by blueagler** [comment]
I noticed the problem. I guess it is because of the user token expire. You can sign out and sign in and refresh the page so it will continue to work. I will try to fix it when I have time.😄

**Comment by batashahh** [comment]
Thankyou for the quick reply. I logged in using another account and it's working fine now.

**Comment by blueagler** [comment]
> Thankyou for the quick reply. I logged in using another account and it's working fine now.
It doesn't matter if you sign in with the account you used before, it will still work.
The problem is on the extension, not on your account

**Comment by blueagler** [comment]
> Thankyou for the quick reply. I logged in using another account and it's working fine now.

It doesn't matter if you sign in with the account you used before, it will still work.
The problem is on the extension, not on your account

**Comment by batashahh** [comment]
Hiya mate! It's happening again. This time the only difference is that the text gets copied into the output window, but does not get paraphrased.

**Comment by blueagler** [comment]
The problem is founded. It can be fixed

**Comment by blueagler** [comment]
> Hiya mate! It's happening again. This time the only difference is that the text gets copied into the output window, but does not get paraphrased.

Problem solved, please clear caches or wait for a day.

**Comment by batashahh** [comment]
Thankyou!

**Comment by roFAAGdev** [comment]
how do i download "Go to the release page next to download the latest version of zip file" ...
