### ISSUE TITLE
The Plagiarism Checker function cannot be used.

### ISSUE THREAD

**Issue by 307677816** [blueagler/QuillBot-Premium-Crack#20]
当我使用Plagiarism Checker功能时，显示剩余可用次数为99999，但是单击《扫描》按钮时，却提示需要购买次数才可以使用，请问怎么能解决^_^

When I use the Plagiarism Checker function, it shows that the remaining available times is 99999, but when I click "Scan" button, it prompts that "Scanning will cost 1 page. Please buy more to continue scanning".

How can I solve this problem?

[Plagiarism Checker](https://quillbot.com/plagiarism-checker)[](https://quillbot.com/plagiarism-checker)

**Comment by mr0xE** [comment]
You will have to buy it
