### ISSUE TITLE
The error message "Premium features are unavailable now, please contact me at Telegram to update new token"

### ISSUE THREAD

**Issue by Emperyal** [blueagler/QuillBot-Premium-Crack#25]
I used this extension for 2 days, and it worked well, but then it stopped working. The site gives an error message saying "Premium features are unavailable now, please contact me at Telegram to update new token." I don't understand. What should I do now?

**Comment by Malkyy** [comment]
did u find a solution ?? my version did the same thing

**Comment by Emperyal** [comment]
> did u find a solution ?? my version did the same thing

It directed me to the Telegram group QuillBot Premium Crack. You have to wait until the admin updates their token. But I bought a new account for this time without waiting.

**Comment by LindaXu1990** [comment]
> 



> > did u find a solution ?? my version did the same thing
> 
> It directed me to the Telegram group QuillBot Premium Crack. You have to wait until the admin updates their token. But I bought a new account for this time without waiting.

How did you buy a new account? Just pay for the official version?

**Comment by ifexalex** [comment]
A quick fix is to sign in with your google or create an account and sign in.

**Comment by blueagler** [comment]
Updated
