### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kuro2701** [blueagler/QuillBot-Premium-Crack#27]
"Premium features are unavailable now, please contact me at Telegram to update new token"
it keeps on appearing boss i think it is not working now

**Comment by xxprozaixx** [comment]
same

**Comment by Malkyy** [comment]
same here

**Comment by LeabaeL** [comment]
me too

**Comment by blueagler** [comment]
Try the new version. Emm token is expensive and I have no benefits
