### ISSUE TITLE
Quillbot issue

### ISSUE THREAD

**Issue by nIk91aaaa** [blueagler/QuillBot-Premium-Crack#32]
![gggggg](https://user-images.githubusercontent.com/113823039/193467275-917f0d98-da05-4993-b88a-e28302916cde.png)
please fix this issue ty:)

**Comment by killlowkey** [comment]
For this problem, you can set the "manifest_version" value to 3, and then it will work well.
```json
{
  "name": "QuillBot Crack",
  "version": "2.0",
  "description": "To unlock the QuillBot Premium",
  "manifest_version": 3,
  "content_scripts": [
    {
      "matches": [
        "https://quillbot.com/*"
      ],
      "js": [
        "./content.js"
      ],
      "run_at": "document_idle",
      "all_frames": true
    }
  ]
}
```

**Comment by zaynjl** [comment]
> For this problem, you can set the "manifest_version" value to 3, and then it will work well.
> 
> ```json
> {
>   "name": "QuillBot Crack",
>   "version": "2.0",
>   "description": "To unlock the QuillBot Premium",
>   "manifest_version": 3,
>   "content_scripts": [
>     {
>       "matches": [
>         "https://quillbot.com/*"
>       ],
>       "js": [
>         "./content.js"
>       ],
>       "run_at": "document_idle",
>       "all_frames": true
>     }
>   ]
> }
> ```

How?

**Comment by killlowkey** [comment]
It doesn‘t work currently; please wait for autor to fix it.

**Comment by muluk2121** [comment]
hello how to fix this problem Premium features are unavailable now, please contact me at Telegram to update new token when i try to open quillbot

**Comment by JosieCen** [comment]
> hello how to fix this problem Premium features are unavailable now, please contact me at Telegram to update new token when i try to open quillbot

I have the same issue. Have you fixed it yet?

**Comment by opop104** [comment]
Refused to load the script 'https://script.blueagle.top/chrome_extension/quillbot.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by blueagler** [comment]
Updated
