### ISSUE TITLE
Premium features are not working anymore.

### ISSUE THREAD

**Issue by ChrisVineyard-abc** [blueagler/QuillBot-Premium-Crack#4]
![Screenshot 2021-12-25 190457](https://user-images.githubusercontent.com/26359923/147384511-b371ec87-e9de-44ee-8bda-b26d528d6b34.png)

I have already signed out and then signed in. But it seems not working anymore. Pls, take a look at this problem. :(

**Comment by blueagler** [comment]
<img width="831" alt="Screen Shot 2021-12-25 at 8 10 21 PM" src="https://user-images.githubusercontent.com/61572188/147384592-d78faaf7-6b69-4517-b054-dcd260968abc.png">
Look at the README Page...

**Comment by ChrisVineyard-abc** [comment]
> <img alt="Screen Shot 2021-12-25 at 8 10 21 PM" width="831" src="https://user-images.githubusercontent.com/61572188/147384592-d78faaf7-6b69-4517-b054-dcd260968abc.png">
> 
> Look at the README Page...

Oooppsss, sorry my bad, hehe. Btw You are the best, I like this project. Keep going. Merry Christmas 🥳🥳🥳
