### ISSUE TITLE
not working:/

### ISSUE THREAD

**Issue by roFAAGdev** [blueagler/QuillBot-Premium-Crack#5]
done everything right unpacked file see your github in top right , ive also logged in it just loads and loads when i click paraphrase does it just not work anymore? it wont even let me logout , please let me know would very much appreciate it

**Comment by blueagler** [comment]
<img width="1792" alt="Screen Shot 2022-01-06 at 5 57 05 PM" src="https://user-images.githubusercontent.com/61572188/148364796-9591fa37-9739-4746-8147-fe7a02f6411a.png">
At there (click right nav)
