### ISSUE TITLE
perpetual loading

### ISSUE THREAD

**Issue by WithdrawalLimits** [blueagler/QuillBot-Premium-Crack#6]
good morning sorry to bother , but it just keeps loading forever, even if i leave it for 12 hours it"ll load plz help me  I appreciate your innovation

**Comment by blueagler** [comment]
First, you can try to log out and log in again.
<img width="1792" alt="Screen Shot 2022-01-19 at 4 26 42 PM" src="https://user-images.githubusercontent.com/61572188/150092405-62686372-0b09-4844-8644-11e60f0c9dc6.png">
 
If it doesn't work, try to clear data and cache of QuillBot
<img width="1791" alt="Screen Shot 2022-01-19 at 4 29 32 PM" src="https://user-images.githubusercontent.com/61572188/150092891-b0794daf-c3a7-4ba9-a314-ec0d733362e4.png">

**Comment by WithdrawalLimits** [comment]
I did & nothing happened & I  can't logout cause it starts loading before I can even try

**Comment by blueagler** [comment]
does quillbot work without the extension？

**Comment by WithdrawalLimits** [comment]
Yeah it does work without the extension

**Comment by blueagler** [comment]
are you using chrome? or Firefox9.4 with windows8.1

**Comment by blueagler** [comment]
can you give a screenshot of the console?

**Comment by WithdrawalLimits** [comment]
yes im using chrome

**Comment by roFAAGdev** [comment]
you recommend just using a different browser or something ?

**Comment by blueagler** [comment]
you gave no picture with no detail describe how can i help you？
